[package]
name = "optimise"
version = "0.1.0"
edition = "2021"


[dependencies]
arithmetic-parser = "0.3.0"
nalgebra = "0.33.0"
plotly = {version = "0.8.4", features=["ndarray"]}
proptest = "1.5.0"
replace_with = "0.1.7"
